// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderSide } from "./OrderSide";

export type CreateOrderRequest = {
  ticker: string;
  amount: number;
  side: OrderSide;
};
